import turtle
turtle.shape('turtle')
finn = turtle.clone()
finn.shape('square')
finn.goto(100,0)
finn.goto(100,0)
finn.goto(100,100)
id1 = finn.stamp()
finn.goto(0,100)
finn.goto(0,0)
finn.goto(-50,0)
id2 = finn.stamp()
charlie = turtle.clone()
charlie.shape('triangle')
charlie.goto(50,50)
charlie.goto(100,0)
finn.goto(-50,-100)
id2 = finn.stamp()
finn.clearstamps()
finn.color('white')
finn.shape('blank')
finn.penup()
turtle.mainloop()
